# Generated by Django 2.1 on 2018-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(blank=True, default=None, max_length=12)),
                ('bank_id', models.IntegerField(blank=True, default=None)),
                ('branch', models.CharField(blank=True, default=None, max_length=80)),
                ('address', models.CharField(blank=True, default=None, max_length=200)),
                ('city', models.CharField(blank=True, default=None, max_length=50)),
                ('district', models.CharField(blank=True, default=None, max_length=50)),
                ('state', models.CharField(blank=True, default=None, max_length=26)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
    ]
